#!/usr/bin/bash


clear && sleep 1
gradle clean
clear && sleep 1
gradle build
clear && sleep 1
rm -rfv output
mkdir -p output
cp /home/nonaybay/Projects/nonaybay-empty-app/app/build/outputs/apk/debug/*.apk /home/nonaybay/Projects/nonaybay-empty-app/output/
cp /home/nonaybay/Projects/nonaybay-empty-app/app/build/outputs/apk/debug/*.apk /home/nonaybay/Projects/nonaybay-empty-app/output/

cd /home/nonaybay/Projects/nonaybay-empty-app/output/

for app in *.apk; do nnb-apkinfo $app; done
